name: GitHub Actions Develop Event
run-name: ${{ github.actor }} is testing out GitHub Develop Actions 🚀
on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 18.13.0 ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM
        run: npm i